USE [DWSales]
GO

/****** Object:  StoredProcedure [dbo].[spETL_OPPORTUNITY]    Script Date: 2/20/2020 5:11:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Jimmy Nguyen
-- Create date: 2020-02-18
-- Data Source: DWSales.stage.STAGE_OPPORTUNITY_SERVICE_ITEM
-- Data Destination: DWSales.sales.OPPORTUNITY
-- Description: This query loads the sales.OPPORTUNITY table in the DWSales database              
-- Change Log: Who, What, When, What   

-- =============================================
CREATE PROCEDURE [dbo].[spETL_OPPORTUNITY]

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	IF((SELECT COUNT(*) FROM DWSales.stage.STAGE_OPPORTUNITY_SERVICE_ITEM) > 2)
        BEGIN
                Alter Table DWSales.sales.OPPORTUNITY_SERVICE_ITEM Drop Constraint IF EXISTS FK_OPPORTUNITY_SERVICE_ITEM_OPPORTUNITY
                Alter Table DWSales.sales.OPPORTUNITY_MEETING_BRIDGE Drop Constraint IF EXISTS FK_OPPORTUNITY_MEETING_BRIDGE_OPPORTUNITY
				TRUNCATE TABLE DWSales.sales.OPPORTUNITY
                
				INSERT INTO DWSales.sales.OPPORTUNITY (OPPORTUNITY_ID, ACTIVITY_CONTEXT, CREATION_DATE_TIME, ESTIMATED_COMPLETION_DATE, CLOSE_DATE_TIME, CLOSE_YEAR_MONTH, LAST_MODIFICATION_DATE_TIME, ESTIMATED_TOTAL_MONTHLY_REVENUE_FROM_SERVICE_ITEMS_AMOUNT, ESTIMATED_TOTAL_MONTHLY_REVENUE_FROM_SERVICE_ITEMS_CURRENCY_CODE, GCI_NUMBER, CLIENT_KEY, INVESTMENT_AND_DESIRABILITY_CODE, IS_PROJECT_BASED, IS_REQUEST_FOR_INFORMATION, IS_REQUEST_FOR_PRICE, IS_REQUEST_FOR_QUOTE, LEGAL_NAME, OPPORTUNITY_DESCRIPTION, OPPORTUNITY_OWNER_ID, OPPORTUNITY_OWNER_BRANCH, OPPORTUNITY_OWNER_BRANCH_KEY, OPPORTUNITY_STATUS_CHANGE_DATE_TIME, OPPORTUNITY_STATUS_CODE, OPPORTUNITY_STEP_PROGRESSION_CODE, OPPORTUNITY_STEP_PROGRESSION_CODE_CHANGE_DATE_TIME, OPPORTUNITY_TYPE_CODE, OPPORTUNITY_TYPE_CODE_CHANGE_DATE_TIME, OWNING_BRANCH_CODE, PERCENT_OF_ESTIMATED_MONTHLY_REVENUE_FROM_INCUMBENCY_CODE, PRIMARY_FOCUS_CODE, SEGMENTATION_CODE, TRANSITION_STATUS_CODE, USER_ESTIMATED_TOTAL_MONTHLY_REVENUE_AMOUNT, USER_ESTIMATED_TOTAL_MONTHLY_REVENUE_AMOUNT_CURRENCY_CODE, TRANSITION_STATUS_SET_TIME, ACCOUNT_ID, ACCOUNT_NAME, CUSTOMER_ACCOUNT_MANAGEMENT_LEVEL_CODE, ACTUAL_BID_KICK_OFF_DATE, BID_RECEIVED_ACT_DATE, BID_RECEIVED_EST_DATE, BID_ROUND_ACTUAL_COMPLETION_DATE, BID_ROUND_ESTIMATED_COMPLETION_DATE, BID_ROUND_NUMBER, CUSTOMER_DEBRIEF_ACTUAL_DATE, CUSTOMER_DEBRIEF_ESTIMATED_DATE, ESTIMATED_BID_KICK_OFF_DATE, INVOLVED_BRANCHES, OUTCOME_RECEIVED_ACTUAL_DATE, OUTCOME_RECEIVED_ESTIMATED_DATE, PRODUCTS_AIR_FLAG_YN, PRODUCTS_CUSTOMS_FLAG_YN, PRODUCTS_DISTRIBUTION_FLAG_YN, PRODUCTS_OCEAN_FLAG_YN, PRODUCTS_ORDER_MANAGEMENT_FLAG_YN, PRODUCTS_OTHER_FLAG_YN, PRODUCTS_PROJECT_CARGO_FLAG_YN, PRODUCTS_TRANSCON_FLAG_YN, PRODUCT_CODES_FROM_BID, INDUSTRY_DESCRIPTION, REASON_LOST_DESCRIPTION, VERTICAL_INDUSTRY_TEAM_CODE, ACCOUNT_STATUS, CUSTOMER_ACCOUNT_OWNER_EMPLOYEE_ID, CUSTOMER_ACCOUNT_OWNER_NAME, EXTERNAL_CONTACT_NAMES, DUNS_NUMBER, PRODUCTS_INSURANCE_FLAG_YN, PRODUCT_CODES_FROM_USER, PRODUCTS_BID_AIR_FLAG_YN, PRODUCTS_BID_CUSTOMS_FLAG_YN, PRODUCTS_BID_DISTRIBUTION_FLAG_YN, PRODUCTS_BID_INSURANCE_FLAG_YN, PRODUCTS_BID_OCEAN_FLAG_YN, PRODUCTS_BID_ORDER_MANAGEMENT_FLAG_YN, PRODUCTS_BID_OTHER_FLAG_YN, PRODUCTS_BID_PROJECT_CARGO_FLAG_YN, PRODUCTS_BID_TRANSCON_FLAG_YN, STEP_PROGRESSION_CODE_20_DATE_TIME, STEP_PROGRESSION_CODE_50_DATE_TIME, STEP_PROGRESSION_CODE_70_DATE_TIME, STEP_PROGRESSION_CODE_90_DATE_TIME, STEP_PROGRESSION_CODE_100_DATE_TIME, STEP_PROGRESSION_CODE_20_DAYS_ON_HOLD, OPPORTUNITY_MEETING_COUNT, OPPORTUNITY_FIRST_COMPLETED_MTG_START_DATE, OPPORTUNITY_LAST_COMPLETED_MTG_START_DATE, OPPORTUNITY_NEXT_COMPLETED_SCHEDULED_START_DATE, NEW_OR_OTHER, NAMED_ACCOUNT_FLAG)
                SELECT  DISTINCT 
                osi.OPPORTUNITY_ID, 
                osi.ACTIVITY_CONTEXT, 
                osi.CREATION_DATE_TIME, 
                CASE WHEN osi.ESTIMATED_COMPLETION_DATE = '1899-12-30' THEN NULL ELSE osi.ESTIMATED_COMPLETION_DATE END AS ESTIMATED_COMPLETION_DATE, 
                CASE WHEN osi.CLOSE_DATE_TIME = '1899-12-30 00:00:00' THEN NULL ELSE osi.CLOSE_DATE_TIME END AS CLOSE_DATE_TIME, 
                CASE WHEN osi.CLOSE_YEAR_MONTH = 0 THEN NULL ELSE osi.CLOSE_YEAR_MONTH END AS CLOSE_YEAR_MONTH, 
                osi.OPPORTUNITY_LAST_MODIFICATION_DATE_TIME AS LAST_MODIFICATION_DATE_TIME, 
                COALESCE(osi.ESTIMATED_TOTAL_MONTHLY_REVENUE_FROM_SERVICE_ITEMS_AMOUNT,0) AS ESTIMATED_TOTAL_MONTHLY_REVENUE_FROM_SERVICE_ITEMS_AMOUNT , 
                CASE WHEN osi.ESTIMATED_TOTAL_MONTHLY_REVENUE_FROM_SERVICE_ITEMS_CURRENCY_CODE = '' THEN NULL ELSE osi.ESTIMATED_TOTAL_MONTHLY_REVENUE_FROM_SERVICE_ITEMS_CURRENCY_CODE END AS ESTIMATED_TOTAL_MONTHLY_REVENUE_FROM_SERVICE_ITEMS_CURRENCY_CODE, 
                osi.GCI_NUMBER, 
                client.CLIENT_KEY,
                CASE WHEN osi.INVESTMENT_AND_DESIRABILITY_CODE = '' THEN NULL ELSE osi.INVESTMENT_AND_DESIRABILITY_CODE END AS INVESTMENT_AND_DESIRABILITY_CODE, 
                osi.IS_PROJECT_BASED, 
                osi.IS_REQUEST_FOR_INFORMATION, 
                osi.IS_REQUEST_FOR_PRICE, 
                osi.IS_REQUEST_FOR_QUOTE, 
                CASE WHEN osi.LEGAL_NAME = '' THEN NULL ELSE osi.LEGAL_NAME END AS LEGAL_NAME, 
                CASE WHEN osi.OPPORTUNITY_DESCRIPTION = '' THEN NULL ELSE osi.OPPORTUNITY_DESCRIPTION END AS OPPORTUNITY_DESCRIPTION, 
                osi.OPPORTUNITY_OWNER_ID, 
                CASE WHEN osi.OPPORTUNITY_OWNER_BRANCH = '' THEN NULL ELSE osi.OPPORTUNITY_OWNER_BRANCH END AS OPPORTUNITY_OWNER_BRANCH,
                bd.BRANCH_KEY AS OPPORTUNITY_OWNER_BRANCH_KEY,
                CASE WHEN osi.OPPORTUNITY_STATUS_CHANGE_DATE_TIME = '1899-12-30 00:00:00' THEN NULL ELSE osi.OPPORTUNITY_STATUS_CHANGE_DATE_TIME END AS OPPORTUNITY_STATUS_CHANGE_DATE_TIME, 
                osi.OPPORTUNITY_STATUS_CODE, 
                osi.OPPORTUNITY_STEP_PROGRESSION_CODE, 
                CASE WHEN osi.OPPORTUNITY_STEP_PROGRESSION_CODE_CHANGE_DATE_TIME = '1899-12-30 00:00:00' THEN NULL ELSE osi.OPPORTUNITY_STEP_PROGRESSION_CODE_CHANGE_DATE_TIME END AS OPPORTUNITY_STEP_PROGRESSION_CODE_CHANGE_DATE_TIME , 
                osi.OPPORTUNITY_TYPE_CODE, 
                CASE WHEN osi.OPPORTUNITY_TYPE_CODE_CHANGE_DATE_TIME = '1899-12-30 00:00:00' THEN NULL ELSE osi.OPPORTUNITY_TYPE_CODE_CHANGE_DATE_TIME END AS OPPORTUNITY_TYPE_CODE_CHANGE_DATE_TIME, 
                CASE WHEN osi.OWNING_BRANCH_CODE = '' THEN NULL ELSE osi.OWNING_BRANCH_CODE END AS OWNING_BRANCH_CODE, 
                CASE WHEN osi.PERCENT_OF_ESTIMATED_MONTHLY_REVENUE_FROM_INCUMBENCY_CODE = '' THEN NULL ELSE osi.PERCENT_OF_ESTIMATED_MONTHLY_REVENUE_FROM_INCUMBENCY_CODE END AS PERCENT_OF_ESTIMATED_MONTHLY_REVENUE_FROM_INCUMBENCY_CODE , 
                CASE WHEN osi.PRIMARY_FOCUS_CODE = '' THEN NULL ELSE osi.PRIMARY_FOCUS_CODE END AS PRIMARY_FOCUS_CODE , 
                CASE WHEN osi.SEGMENTATION_CODE = '' THEN NULL ELSE osi.SEGMENTATION_CODE  END AS SEGMENTATION_CODE , 
                CASE WHEN osi.TRANSITION_STATUS_CODE = '' THEN NULL ELSE osi.TRANSITION_STATUS_CODE END AS TRANSITION_STATUS_CODE , 
                osi.USER_ESTIMATED_TOTAL_MONTHLY_REVENUE_AMOUNT, 
                osi.USER_ESTIMATED_TOTAL_MONTHLY_REVENUE_AMOUNT_CURRENCY_CODE, 
                CASE WHEN osi.TRANSITION_STATUS_SET_TIME = '1899-12-30 00:00:00' THEN NULL ELSE osi.TRANSITION_STATUS_SET_TIME END AS TRANSITION_STATUS_SET_TIME, 
                CASE WHEN osi.ACCOUNT_ID = '' THEN NULL ELSE osi.ACCOUNT_ID  END AS ACCOUNT_ID, 
                CASE WHEN osi.ACCOUNT_NAME = '' THEN NULL ELSE osi.ACCOUNT_NAME END AS ACCOUNT_NAME, 
                CASE WHEN osi.CUSTOMER_ACCOUNT_MANAGEMENT_LEVEL_CODE = '' THEN NULL ELSE osi.CUSTOMER_ACCOUNT_MANAGEMENT_LEVEL_CODE END AS CUSTOMER_ACCOUNT_MANAGEMENT_LEVEL_CODE, 
                --CLIENT_KEY, 
                CASE WHEN osi.ACTUAL_BID_KICK_OFF_DATE = '1899-12-30' THEN NULL ELSE osi.ACTUAL_BID_KICK_OFF_DATE END AS ACTUAL_BID_KICK_OFF_DATE , 
                CASE WHEN osi.BID_RECEIVED_ACT_DATE = '1899-12-30' THEN NULL ELSE osi.BID_RECEIVED_ACT_DATE END AS BID_RECEIVED_ACT_DATE, 
                CASE WHEN osi.BID_RECEIVED_EST_DATE = '1899-12-30' THEN NULL ELSE osi.BID_RECEIVED_EST_DATE END AS BID_RECEIVED_EST_DATE, 
                CASE WHEN osi.BID_ROUND_ACTUAL_COMPLETION_DATE = '1899-12-30' THEN NULL ELSE osi.BID_ROUND_ACTUAL_COMPLETION_DATE END AS BID_ROUND_ACTUAL_COMPLETION_DATE, 
                CASE WHEN osi.BID_ROUND_ESTIMATED_COMPLETION_DATE = '1899-12-30' THEN NULL ELSE osi.BID_ROUND_ESTIMATED_COMPLETION_DATE  END AS BID_ROUND_ESTIMATED_COMPLETION_DATE , 
                osi.BID_ROUND_NUMBER, 
                CASE WHEN osi.CUSTOMER_DEBRIEF_ACTUAL_DATE = '1899-12-30' THEN NULL ELSE osi.CUSTOMER_DEBRIEF_ACTUAL_DATE END AS CUSTOMER_DEBRIEF_ACTUAL_DATE, 
                CASE WHEN osi.CUSTOMER_DEBRIEF_ESTIMATED_DATE = '1899-12-30' THEN NULL ELSE osi.CUSTOMER_DEBRIEF_ESTIMATED_DATE END AS CUSTOMER_DEBRIEF_ESTIMATED_DATE, 
                CASE WHEN osi.ESTIMATED_BID_KICK_OFF_DATE = '1899-12-30' THEN NULL ELSE osi.ESTIMATED_BID_KICK_OFF_DATE END AS ESTIMATED_BID_KICK_OFF_DATE, 
                CASE WHEN osi.INVOLVED_BRANCHES = '' THEN NULL ELSE osi.INVOLVED_BRANCHES END AS INVOLVED_BRANCHES, 
                CASE WHEN osi.OUTCOME_RECEIVED_ACTUAL_DATE = '1899-12-30' THEN NULL ELSE osi.OUTCOME_RECEIVED_ACTUAL_DATE END AS OUTCOME_RECEIVED_ACTUAL_DATE, 
                CASE WHEN osi.OUTCOME_RECEIVED_ESTIMATED_DATE = '1899-12-30' THEN NULL ELSE osi.OUTCOME_RECEIVED_ESTIMATED_DATE END AS OUTCOME_RECEIVED_ESTIMATED_DATE, 
                osi.PRODUCTS_AIR_FLAG_YN, 
                osi.PRODUCTS_CUSTOMS_FLAG_YN, 
                osi.PRODUCTS_DISTRIBUTION_FLAG_YN, 
                osi.PRODUCTS_OCEAN_FLAG_YN, 
                osi.PRODUCTS_ORDER_MANAGEMENT_FLAG_YN, 
                osi.PRODUCTS_OTHER_FLAG_YN, 
                osi.PRODUCTS_PROJECT_CARGO_FLAG_YN, 
                osi.PRODUCTS_TRANSCON_FLAG_YN, 
                CASE WHEN osi.PRODUCT_CODES_FROM_BID = '' THEN NULL ELSE osi.PRODUCT_CODES_FROM_BID END AS PRODUCT_CODES_FROM_BID, 
                CASE WHEN osi.INDUSTRY_DESCRIPTION = '' THEN NULL ELSE osi.INDUSTRY_DESCRIPTION END AS INDUSTRY_DESCRIPTION, 
                CASE WHEN osi.REASON_LOST_DESCRIPTION = '' THEN NULL ELSE osi.REASON_LOST_DESCRIPTION END AS REASON_LOST_DESCRIPTION,
                CASE WHEN osi.VERTICAL_INDUSTRY_TEAM_CODE = '' THEN NULL ELSE osi.VERTICAL_INDUSTRY_TEAM_CODE END AS VERTICAL_INDUSTRY_TEAM_CODE, 
                CASE WHEN osi.ACCOUNT_STATUS = '' THEN NULL ELSE osi.ACCOUNT_STATUS END AS ACCOUNT_STATUS, 
                CASE WHEN osi.CUSTOMER_ACCOUNT_OWNER_EMPLOYEE_ID = 0 THEN NULL ELSE osi.CUSTOMER_ACCOUNT_OWNER_EMPLOYEE_ID END AS CUSTOMER_ACCOUNT_OWNER_EMPLOYEE_ID , 
                CASE WHEN osi.CUSTOMER_ACCOUNT_OWNER_NAME = '' THEN NULL ELSE osi.CUSTOMER_ACCOUNT_OWNER_NAME END AS CUSTOMER_ACCOUNT_OWNER_NAME, 
                osi.EXTERNAL_CONTACT_NAMES, 
                CASE WHEN osi.DUNS_NUMBER = '' THEN NULL ELSE osi.DUNS_NUMBER END AS DUNS_NUMBER, 
                osi.PRODUCTS_INSURANCE_FLAG_YN, 
                osi.PRODUCT_CODES_FROM_USER, 
                osi.PRODUCTS_BID_AIR_FLAG_YN, 
                osi.PRODUCTS_BID_CUSTOMS_FLAG_YN, 
                osi.PRODUCTS_BID_DISTRIBUTION_FLAG_YN, 
                osi.PRODUCTS_BID_INSURANCE_FLAG_YN, 
                osi.PRODUCTS_BID_OCEAN_FLAG_YN, 
                osi.PRODUCTS_BID_ORDER_MANAGEMENT_FLAG_YN, 
                osi.PRODUCTS_BID_OTHER_FLAG_YN, 
                osi.PRODUCTS_BID_PROJECT_CARGO_FLAG_YN, 
                osi.PRODUCTS_BID_TRANSCON_FLAG_YN, 
                CASE WHEN osi.STEP_PROGRESSION_CODE_20_DATE_TIME = '1899-12-30 00:00:00' THEN NULL ELSE osi.STEP_PROGRESSION_CODE_20_DATE_TIME END AS STEP_PROGRESSION_CODE_20_DATE_TIME, 
                CASE WHEN osi.STEP_PROGRESSION_CODE_50_DATE_TIME = '1899-12-30 00:00:00' THEN NULL ELSE osi.STEP_PROGRESSION_CODE_50_DATE_TIME END AS STEP_PROGRESSION_CODE_50_DATE_TIME, 
                CASE WHEN osi.STEP_PROGRESSION_CODE_70_DATE_TIME = '1899-12-30 00:00:00' THEN NULL ELSE osi.STEP_PROGRESSION_CODE_70_DATE_TIME END AS STEP_PROGRESSION_CODE_70_DATE_TIME, 
                CASE WHEN osi.STEP_PROGRESSION_CODE_90_DATE_TIME = '1899-12-30 00:00:00' THEN NULL ELSE osi.STEP_PROGRESSION_CODE_90_DATE_TIME END AS STEP_PROGRESSION_CODE_90_DATE_TIME , 
                CASE WHEN osi.STEP_PROGRESSION_CODE_100_DATE_TIME = '1899-12-30 00:00:00' THEN NULL ELSE osi.STEP_PROGRESSION_CODE_100_DATE_TIME END AS STEP_PROGRESSION_CODE_100_DATE_TIME, 
                osi.STEP_PROGRESSION_CODE_20_DAYS_ON_HOLD, 
                osi.OPPORTUNITY_MEETING_COUNT, 
                CASE WHEN osi.OPPORTUNITY_FIRST_COMPLETED_MTG_START_DATE = '1899-12-30' THEN NULL ELSE osi.OPPORTUNITY_FIRST_COMPLETED_MTG_START_DATE END AS OPPORTUNITY_FIRST_COMPLETED_MTG_START_DATE, 
                CASE WHEN osi.OPPORTUNITY_LAST_COMPLETED_MTG_START_DATE = '1899-12-30' THEN NULL ELSE osi.OPPORTUNITY_LAST_COMPLETED_MTG_START_DATE END AS OPPORTUNITY_LAST_COMPLETED_MTG_START_DATE, 
                CASE WHEN osi.OPPORTUNITY_NEXT_COMPLETED_SCHEDULED_START_DATE = '1899-12-30' THEN NULL ELSE osi.OPPORTUNITY_NEXT_COMPLETED_SCHEDULED_START_DATE END AS OPPORTUNITY_NEXT_COMPLETED_SCHEDULED_START_DATE ,
                pipe.NEW_OR_OTHER,
                pipe.NAMED_ACCOUNT_FLAG
                
                FROM DwSales.stage.STAGE_OPPORTUNITY_SERVICE_ITEM osi
                LEFT JOIN DwSales.dbo.BRANCH_DIMENSION bd
                        ON BD.branch_code = osi.opportunity_owner_branch
                LEFT JOIN (SELECT DISTINCT opportunity_id,named_account_flag, new_or_other FROM Sales.report.CRM_PIPELINE) pipe
                        ON pipe.opportunity_id = osi.opportunity_id
				LEFT JOIN (SELECT client_number, client_key FROM dbo.client_dimension) client
						ON client.client_number = osi.gci_number 
--WHERE osi.opportunity_id = 'OPP0000000368369'
                
           END
END
GO


