USE [DWSales]
GO

/****** Object:  StoredProcedure [dbo].[spETL_OPPORTUNITY_SERVICE_ITEM]    Script Date: 2/20/2020 5:13:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Jimmy Nguyen
-- Create date: 2020-02-18
-- Data Source: DWSales.stage.STAGE_OPPORTUNITY_SERVICE_ITEM
-- Data Destination: DWSales.sales.OPPORTUNITY_SERVICE_ITEM
-- Description: This query loads the sales.OPPORTUNITY_SERVICE_ITEM table in the DWSales database             
-- Change Log: Who, What, When, What   

-- =============================================
CREATE PROCEDURE [dbo].[spETL_OPPORTUNITY_SERVICE_ITEM]

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	IF((SELECT COUNT(*) FROM DWSales.stage.STAGE_OPPORTUNITY_SERVICE_ITEM) > 2)
        BEGIN
                Alter Table DWSales.sales.OPPORTUNITY_SERVICE_ITEM Drop Constraint IF EXISTS FK_OPPORTUNITY_SERVICE_ITEM_OPPORTUNITY
                Alter Table DWSales.sales.OPPORTUNITY_MEETING_BRIDGE Drop Constraint IF EXISTS FK_OPPORTUNITY_MEETING_BRIDGE_OPPORTUNITY
				TRUNCATE TABLE DWSales.sales.OPPORTUNITY_SERVICE_ITEM
                
				INSERT INTO DWSales.sales.OPPORTUNITY_SERVICE_ITEM  (OPPORTUNITY_SERVICE_ITEM_ID, OPPORTUNITY_ID, OPPORTUNITY_KEY, ACTUAL_CLOSE_DATE, DELETION_DATE_TIME, DENSITY_CODE, DESTINATION_PORT_CODE, DESTINATION_BRANCH, ESTIMATED_CLOSE_DATE, IS_DANGEROUS_GOODS, IS_DELIVERY, IS_EXPORT_DECLARATION, IS_IMPORT_DECLARATION, IS_PICKUP, IS_TRANSACTIONAL_INSURANCE, LAST_MODIFICATION_DATE_TIME, OPPORTUNITY_SERVICE_ITEM_PRODUCT_CODE, OPPORTUNITY_SERVICE_ITEM_STATUS_CODE, OPPORTUNITY_SERVICE_ITEM_STEP_PROGRESSION_CODE, ORIGIN_PORT_CODE, ORIGIN_BRANCH, SELL_SERVICE_CODE, SERVICE_LEVEL_CODE, SERVICE_LOCATION_CODE, SERVICE_LOCATION_BRANCH, SERVICE_OFFICE_CODE, SERVICE_OFFICE_BRANCH, SYSTEM_CALCULATED_DESTINATION_MONTHLY_REVENUE_AMOUNT, SYSTEM_CALCULATED_DESTINATION_MONTHLY_REVENUE_CURRENCY_CODE, SYSTEM_CALCULATED_ORIGIN_MONTHLY_REVENUE_AMOUNT, SYSTEM_CALCULATED_ORIGIN_MONTHLY_REVENUE_CURRENCY_CODE, SYSTEM_CALCULATED_SERVICE_LOCATION_MONTHLY_REVENUE_AMOUNT, SYSTEM_CALCULATED_SERVICE_LOCATION_MONTHLY_REVENUE_CURRENCY_CODE, SYSTEM_CALCULATED_SERVICE_OFFICE_MONTHLY_REVENUE_AMOUNT, SYSTEM_CALCULATED_SERVICE_OFFICE_MONTHLY_REVENUE_CURRENCY_CODE, SYSTEM_CALCULATED_TOTAL_ESTIMATED_MONTHLY_REVENUE_AMOUNT, SYSTEM_CALCULATED_TOTAL_ESTIMATED_MONTHLY_REVENUE_CURRENCY_CODE, TRANSACTIONAL_INSURANCE_TOTAL_INSURED_VALUE_AMOUNT, TRANSACTIONAL_INSURANCE_TOTAL_INSURED_VALUE_CURRENCY_CODE, USER_ESTIMATED_DESTINATION_MONTHLY_REVENUE_AMOUNT, USER_ESTIMATED_DESTINATION_MONTHLY_REVENUE_CURRENCY_CODE, USER_ESTIMATED_ORIGIN_MONTHLY_REVENUE_AMOUNT, USER_ESTIMATED_ORIGIN_MONTHLY_REVENUE_CURRENCY_CODE, USER_ESTIMATED_SERVICE_LOCATION_MONTHLY_REVENUE_AMOUNT, USER_ESTIMATED_SERVICE_LOCATION_MONTHLY_REVENUE_CURRENCY_CODE, USER_ESTIMATED_SERVICE_OFFICE_MONTHLY_REVENUE_AMOUNT, USER_ESTIMATED_SERVICE_OFFICE_MONTHLY_REVENUE_CURRENCY_CODE, USER_TOTAL_ESTIMATED_MONTHLY_REVENUE_FROM_USER_ENTERED_REVENUE_AMOUNT, USER_TOTAL_ESTIMATED_MONTHLY_REVENUE_FROM_USER_ENTERED_REVENUE_CURRENCY_CODE, WIN_PROBABILITY_CODE, MONTHLY_QUANTITY, MONTHLY_QUANTITY_UNIT_CODE, MONTHLY_TRANSACTIONS, PERCENT_AWARDED_VOLUME_CODE, PERCENT_INCUMBENCY_CODE, PERCENT_TARGETED_CODE) 
                SELECT DISTINCT 
                        osi.OPPORTUNITY_SERVICE_ITEM_ID, 
                        osi.OPPORTUNITY_ID, 
                        opp.OPPORTUNITY_KEY, 
                        CASE WHEN osi.ACTUAL_CLOSE_DATE = '1899-12-30 00:00:00' THEN NULL ELSE osi.ACTUAL_CLOSE_DATE END AS ACTUAL_CLOSE_DATE , 
                        CASE WHEN osi.DELETION_DATE_TIME = '1899-12-30 00:00:00' THEN NULL ELSE osi.DELETION_DATE_TIME END AS DELETION_DATE_TIME, 
                        CASE WHEN osi.DENSITY_CODE = '' THEN NULL ELSE osi.DENSITY_CODE END AS DENSITY_CODE, 
                        CASE WHEN osi.DESTINATION_PORT_CODE = '' THEN NULL ELSE osi.DESTINATION_PORT_CODE END AS DESTINATION_PORT_CODE, 
                        CASE WHEN osi.DESTINATION_BRANCH = '' THEN NULL ELSE osi.DESTINATION_BRANCH END AS DESTINATION_BRANCH, 
                        CASE WHEN osi.ESTIMATED_CLOSE_DATE = '1899-12-30' THEN NULL ELSE osi.ESTIMATED_CLOSE_DATE END AS ESTIMATED_CLOSE_DATE, 
                        CASE WHEN osi.IS_DANGEROUS_GOODS = '' THEN NULL ELSE osi.IS_DANGEROUS_GOODS END AS IS_DANGEROUS_GOODS , 
                        CASE WHEN osi.IS_DELIVERY = '' THEN NULL ELSE osi.IS_DELIVERY END AS IS_DELIVERY, 
                        CASE WHEN osi.IS_EXPORT_DECLARATION = '' THEN NULL ELSE osi.IS_EXPORT_DECLARATION END AS IS_EXPORT_DECLARATION, 
                        CASE WHEN osi.IS_IMPORT_DECLARATION = '' THEN NULL ELSE osi.IS_IMPORT_DECLARATION END AS IS_IMPORT_DECLARATION , 
                        CASE WHEN osi.IS_PICKUP = '' THEN NULL ELSE osi.IS_PICKUP END AS IS_PICKUP, 
                        CASE WHEN osi.IS_TRANSACTIONAL_INSURANCE = '' THEN NULL ELSE osi.IS_TRANSACTIONAL_INSURANCE END AS IS_TRANSACTIONAL_INSURANCE, 
                        osi.OPPORTUNITY_SERVICE_ITEM_LAST_MODIFICATION_DATE_TIME AS LAST_MODIFICATION_DATE_TIME, 
                        osi.OPPORTUNITY_SERVICE_ITEM_PRODUCT_CODE, 
                        osi.OPPORTUNITY_SERVICE_ITEM_STATUS_CODE, 
                        osi.OPPORTUNITY_SERVICE_ITEM_STEP_PROGRESSION_CODE, 
                        CASE WHEN osi.ORIGIN_PORT_CODE = '' THEN NULL ELSE osi.ORIGIN_PORT_CODE END AS ORIGIN_PORT_CODE, 
                        CASE WHEN osi.ORIGIN_BRANCH = '' THEN NULL ELSE osi.ORIGIN_BRANCH END AS ORIGIN_BRANCH , 
                        CASE WHEN osi.SELL_SERVICE_CODE = '' THEN NULL ELSE osi.SELL_SERVICE_CODE END AS SELL_SERVICE_CODE , 
                        CASE WHEN osi.SERVICE_LEVEL_CODE = '' THEN NULL ELSE osi.SERVICE_LEVEL_CODE END AS SERVICE_LEVEL_CODE, 
                        CASE WHEN osi.SERVICE_LOCATION_CODE = '' THEN NULL ELSE osi.SERVICE_LOCATION_CODE END AS SERVICE_LOCATION_CODE, 
                        CASE WHEN osi.SERVICE_LOCATION_BRANCH = '' THEN NULL ELSE osi.SERVICE_LOCATION_BRANCH END AS SERVICE_LOCATION_BRANCH, 
                        CASE WHEN osi.SERVICE_OFFICE_CODE = '' THEN NULL ELSE osi.SERVICE_OFFICE_CODE END AS SERVICE_OFFICE_CODE, 
                        CASE WHEN osi.SERVICE_OFFICE_BRANCH = '' THEN NULL ELSE osi.SERVICE_OFFICE_BRANCH END AS SERVICE_OFFICE_BRANCH, 
                        osi.SYSTEM_CALCULATED_DESTINATION_MONTHLY_REVENUE_AMOUNT, 
                        CASE WHEN osi.SYSTEM_CALCULATED_DESTINATION_MONTHLY_REVENUE_CURRENCY_CODE = '' THEN NULL ELSE osi.SYSTEM_CALCULATED_DESTINATION_MONTHLY_REVENUE_CURRENCY_CODE END AS SYSTEM_CALCULATED_DESTINATION_MONTHLY_REVENUE_CURRENCY_CODE , 
                        osi.SYSTEM_CALCULATED_ORIGIN_MONTHLY_REVENUE_AMOUNT, 
                        CASE WHEN osi.SYSTEM_CALCULATED_ORIGIN_MONTHLY_REVENUE_CURRENCY_CODE = '' THEN NULL ELSE osi.SYSTEM_CALCULATED_ORIGIN_MONTHLY_REVENUE_CURRENCY_CODE END AS SYSTEM_CALCULATED_ORIGIN_MONTHLY_REVENUE_CURRENCY_CODE, 
                        osi.SYSTEM_CALCULATED_SERVICE_LOCATION_MONTHLY_REVENUE_AMOUNT, 
                        CASE WHEN osi.SYSTEM_CALCULATED_SERVICE_LOCATION_MONTHLY_REVENUE_CURRENCY_CODE = '' THEN NULL ELSE osi.SYSTEM_CALCULATED_SERVICE_LOCATION_MONTHLY_REVENUE_CURRENCY_CODE END AS SYSTEM_CALCULATED_SERVICE_LOCATION_MONTHLY_REVENUE_CURRENCY_CODE, 
                        osi.SYSTEM_CALCULATED_SERVICE_OFFICE_MONTHLY_REVENUE_AMOUNT, 
                        CASE WHEN osi.SYSTEM_CALCULATED_SERVICE_OFFICE_MONTHLY_REVENUE_CURRENCY_CODE = '' THEN NULL ELSE osi.SYSTEM_CALCULATED_SERVICE_OFFICE_MONTHLY_REVENUE_CURRENCY_CODE END AS SYSTEM_CALCULATED_SERVICE_OFFICE_MONTHLY_REVENUE_CURRENCY_CODE, 
                        osi.SYSTEM_CALCULATED_TOTAL_ESTIMATED_MONTHLY_REVENUE_AMOUNT, 
                        CASE WHEN osi.SYSTEM_CALCULATED_TOTAL_ESTIMATED_MONTHLY_REVENUE_CURRENCY_CODE = '' THEN NULL ELSE osi.SYSTEM_CALCULATED_TOTAL_ESTIMATED_MONTHLY_REVENUE_CURRENCY_CODE END AS SYSTEM_CALCULATED_TOTAL_ESTIMATED_MONTHLY_REVENUE_CURRENCY_CODE, 
                        osi.TRANSACTIONAL_INSURANCE_TOTAL_INSURED_VALUE_AMOUNT, 
                        CASE WHEN osi.TRANSACTIONAL_INSURANCE_TOTAL_INSURED_VALUE_CURRENCY_CODE = '' THEN NULL ELSE osi.TRANSACTIONAL_INSURANCE_TOTAL_INSURED_VALUE_CURRENCY_CODE END AS TRANSACTIONAL_INSURANCE_TOTAL_INSURED_VALUE_CURRENCY_CODE, 
                        osi.USER_ESTIMATED_DESTINATION_MONTHLY_REVENUE_AMOUNT, 
                        CASE WHEN osi.USER_ESTIMATED_DESTINATION_MONTHLY_REVENUE_CURRENCY_CODE = '' THEN NULL ELSE osi.USER_ESTIMATED_DESTINATION_MONTHLY_REVENUE_CURRENCY_CODE END AS USER_ESTIMATED_DESTINATION_MONTHLY_REVENUE_CURRENCY_CODE, 
                        osi.USER_ESTIMATED_ORIGIN_MONTHLY_REVENUE_AMOUNT, 
                        CASE WHEN osi.USER_ESTIMATED_ORIGIN_MONTHLY_REVENUE_CURRENCY_CODE = '' THEN NULL ELSE osi.USER_ESTIMATED_ORIGIN_MONTHLY_REVENUE_CURRENCY_CODE END AS USER_ESTIMATED_ORIGIN_MONTHLY_REVENUE_CURRENCY_CODE, 
                        osi.USER_ESTIMATED_SERVICE_LOCATION_MONTHLY_REVENUE_AMOUNT, 
                        CASE WHEN osi.USER_ESTIMATED_SERVICE_LOCATION_MONTHLY_REVENUE_CURRENCY_CODE = '' THEN NULL ELSE osi.USER_ESTIMATED_SERVICE_LOCATION_MONTHLY_REVENUE_CURRENCY_CODE  END AS USER_ESTIMATED_SERVICE_LOCATION_MONTHLY_REVENUE_CURRENCY_CODE , 
                        osi.USER_ESTIMATED_SERVICE_OFFICE_MONTHLY_REVENUE_AMOUNT, 
                        CASE WHEN osi.USER_ESTIMATED_SERVICE_OFFICE_MONTHLY_REVENUE_CURRENCY_CODE = '' THEN NULL ELSE osi.USER_ESTIMATED_SERVICE_OFFICE_MONTHLY_REVENUE_CURRENCY_CODE END AS USER_ESTIMATED_SERVICE_OFFICE_MONTHLY_REVENUE_CURRENCY_CODE, 
                        osi.USER_TOTAL_ESTIMATED_MONTHLY_REVENUE_FROM_USER_ENTERED_REVENUE_AMOUNT, 
                        CASE WHEN osi.USER_TOTAL_ESTIMATED_MONTHLY_REVENUE_FROM_USER_ENTERED_REVENUE_CURRENCY_CODE = '' THEN NULL ELSE osi.USER_TOTAL_ESTIMATED_MONTHLY_REVENUE_FROM_USER_ENTERED_REVENUE_CURRENCY_CODE END AS USER_TOTAL_ESTIMATED_MONTHLY_REVENUE_FROM_USER_ENTERED_REVENUE_CURRENCY_CODE, 
                        CASE WHEN osi.WIN_PROBABILITY_CODE = '' THEN NULL ELSE osi.WIN_PROBABILITY_CODE END AS WIN_PROBABILITY_CODE, 
                        osi.MONTHLY_QUANTITY, 
                        CASE WHEN osi.MONTHLY_QUANTITY_UNIT_CODE = '' THEN NULL ELSE osi.MONTHLY_QUANTITY_UNIT_CODE END AS MONTHLY_QUANTITY_UNIT_CODE, 
                        osi.MONTHLY_TRANSACTIONS, 
                        CASE WHEN osi.PERCENT_AWARDED_VOLUME_CODE = '' THEN NULL ELSE osi.PERCENT_AWARDED_VOLUME_CODE END AS PERCENT_AWARDED_VOLUME_CODE, 
                        CASE WHEN osi.PERCENT_INCUMBENCY_CODE = '' THEN NULL ELSE osi.PERCENT_INCUMBENCY_CODE END AS PERCENT_INCUMBENCY_CODE, 
                        CASE WHEN osi.PERCENT_TARGETED_CODE = '' THEN NULL ELSE osi.PERCENT_TARGETED_CODE END AS PERCENT_TARGETED_CODE
                        FROM DWSales.stage.STAGE_OPPORTUNITY_SERVICE_ITEM osi
                        INNER JOIN DwSales.sales.OPPORTUNITY opp
                                ON opp.opportunity_id = osi.opportunity_id
                        WHERE osi.opportunity_service_item_id <> ''
                        
        END
END
GO


